###################################################
#		docker-compose
###################################################

version: '3.0'

services:
   nxapp:
     #env_file:
     # - variables.env
     build: .
     ports:
      - "8080:8080"